CREATE TABLE `RESERVATION_DATE` (
  `NAME` VARCHAR(255) NOT NULL,
  `DATE` DATE NOT NULL,
  `RESERVATION_TIME` CHAR(1) NOT NULL,
  `CREATEDA_AT` DATE NOT NULL,
  `UPDATED_AT` DATE NOT NULL,
  PRIMARY KEY(NAME,DATE,RESERVATION_TIME)
);